# Contenido del sitio. Todo lo que se publica sale de aquí: si cambia un texto, se cambia aquí
# y se vuelve a generar con `python3 _fuente/construir.py`.
# Regla: sin cifras, clientes ni testimonios inventados. Lo que no está confirmado lleva «POR CONFIRMAR» en el reporte.

WA_NUM = '523114469363'
TEL = '+52 311 446 9363'

# Piezas del estimador (horas para negocio micro). Fuente: página publicada, oct-2026.
PIEZAS = [
    ('orden', 1, False, 'Lista de precios o catálogo', 'Que todos vean el mismo producto y el mismo precio.'),
    ('orden', 2, True, 'Cotizador', 'Decir qué se entrega, cuánto cuesta y hasta cuándo vale el precio.'),
    ('orden', 4, True, 'Procedimiento escrito', 'Mostrar cómo hacer la tarea sin depender de la memoria.'),
    ('orden', 3, False, 'Quién hace qué', 'Que cada pendiente tenga una persona responsable.'),
    ('orden', 4, False, 'Expediente para el contador', 'Tener juntos los documentos que necesita tu contador.'),
    ('visibilidad', 2, True, 'Control de pedidos y cobros', 'Saber qué se pidió, qué se entregó y cuánto falta cobrar.'),
    ('visibilidad', 4, True, 'Registro diario desde el celular', 'Guardar el dato antes de olvidarlo.'),
    ('visibilidad', 4, True, 'Flujo a 30, 60 y 90 días', 'Ver si el dinero alcanzaría en las próximas fechas.'),
    ('visibilidad', 5, True, 'Tablero semanal', 'Ver lo más urgente sin leer todos los registros.'),
    ('visibilidad', 5, True, 'Inventario y reorden', 'Tener existencias visibles y pedir antes de quedarte sin producto.'),
    ('control', 2, True, 'Agenda de cobranza', 'Saber a quién cobrar, cuánto y cuándo.'),
    ('control', 4, False, 'Lo cobrado contra lo depositado', 'Comprobar que lo que cobraste coincide con lo que entró al banco.'),
    ('control', 2, True, 'Arqueo y cierre de caja', 'Cerrar el día con la caja contada y comparada.'),
]
PIEZA = {p[3]: p for p in PIEZAS}
PILAR_NOMBRE = {'orden': 'Orden', 'visibilidad': 'Visibilidad', 'control': 'Control', 'mejora': 'Mejora continua'}

# ---------------- Industrias ----------------
INDUSTRIAS = [
    dict(slug='alimentos-y-bebidas', corto='Restaurantes, cafeterías, panaderías y más.', nombre='Alimentos y bebidas',
         tipos='Restaurantes, cocinas económicas, cafeterías, panaderías, tortillerías y purificadoras.',
         lead='Vendes todo el día, en efectivo y por transferencia, con insumos que caducan. Te ayudamos a que la caja cuadre, el inventario avise a tiempo y cada turno trabaje igual.',
         voces=['¿Por qué no me cuadra la caja al cierre?', '¿Qué tengo que comprar para mañana?', '¿Cómo hago que el turno de la tarde trabaje igual que el de la mañana?', '¿Cuánto vendí esta semana contra la pasada?'],
         piezas=['Arqueo y cierre de caja', 'Lo cobrado contra lo depositado', 'Inventario y reorden', 'Procedimiento escrito', 'Registro diario desde el celular', 'Lista de precios o catálogo'],
         herramientas=['Hojas de Google', 'Excel', 'WhatsApp Business', 'Canva', 'Mercado Pago', 'Google Maps']),
    dict(slug='comercio-y-tiendas', corto='Abarrotes, ferreterías, papelerías y farmacias.', nombre='Comercio y tiendas',
         tipos='Abarrotes, ferreterías, papelerías, farmacias, boutiques y materiales.',
         lead='Muchos productos, precios que cambian y clientes que piden fiado. Ordenamos tu lista de precios, tu inventario y tu cobranza para que sepas qué tienes y quién te debe.',
         voces=['¿Qué tengo y qué necesito comprar?', '¿Quién me debe y desde cuándo?', '¿Todos mis empleados dan el mismo precio?', '¿Cuánto vendí esta semana contra la pasada?'],
         piezas=['Lista de precios o catálogo', 'Inventario y reorden', 'Agenda de cobranza', 'Tablero semanal', 'Arqueo y cierre de caja', 'Cotizador'],
         herramientas=['Excel', 'Hojas de Google', 'WhatsApp Business', 'Canva', 'Mercado Pago', 'CONTPAQi', 'Aspel']),
    dict(slug='distribucion-y-logistica', corto='Distribuidoras, repartidores y fleteras.', nombre='Distribución y logística',
         tipos='Distribuidoras, repartidores, fleteras y mensajería local.',
         lead='Pedidos, rutas y cobros que se cruzan. Hacemos visible qué falta entregar, a qué hora y qué falta cobrar, para que el dinero de la ruta llegue completo.',
         voces=['¿Qué falta entregar y a qué hora?', '¿Qué pedido ya se entregó y cuál no se ha cobrado?', '¿Quién trae el efectivo de la ruta?', '¿Me alcanza para pagar a proveedores este mes?'],
         piezas=['Control de pedidos y cobros', 'Agenda de cobranza', 'Lo cobrado contra lo depositado', 'Flujo a 30, 60 y 90 días', 'Quién hace qué', 'Tablero semanal'],
         herramientas=['Hojas de Google', 'Google Maps', 'WhatsApp Business', 'Google Forms', 'Excel', 'Odoo']),
    dict(slug='construccion-e-ingenieria', corto='Contratistas, herrerías y despachos de proyecto.', nombre='Construcción e ingeniería',
         tipos='Contratistas, constructoras pequeñas, herrerías, carpinterías y despachos de proyecto.',
         lead='Cada obra es un proyecto con material, cuadrillas y pagos por avance. Te ayudamos a saber quién hace qué, para cuándo, y si el dinero alcanza hasta el siguiente pago del cliente.',
         voces=['¿Quién hace qué y para cuándo?', '¿Cuánto material se fue en esta obra?', '¿Me alcanza el dinero hasta el próximo pago del cliente?', '¿Qué falta cobrar de cada obra?'],
         piezas=['Quién hace qué', 'Cotizador', 'Flujo a 30, 60 y 90 días', 'Control de pedidos y cobros', 'Expediente para el contador', 'Procedimiento escrito'],
         herramientas=['Excel', 'Hojas de Google', 'Google Drive', 'WhatsApp Business', 'Trello', 'Canva']),
    dict(slug='fabricacion-y-produccion', corto='Producción por lotes o por encargo.', nombre='Fabricación y producción',
         tipos='Talleres de producción, maquila, muebles, alimentos procesados y producción por lotes o por encargo.',
         lead='Producir bien y a tiempo depende de saber qué pedido sigue, cuánto material se va en cada lote y quién responde por cada paso.',
         voces=['¿Qué pedido toca entregar primero?', '¿Cuánto material se va en cada lote?', '¿Por qué sale distinto el mismo producto?', '¿Qué falta comprar para la producción de la semana?'],
         piezas=['Procedimiento escrito', 'Inventario y reorden', 'Control de pedidos y cobros', 'Tablero semanal', 'Quién hace qué', 'Cotizador'],
         herramientas=['Excel', 'Hojas de Google', 'Odoo', 'Google Forms', 'WhatsApp Business', 'Power BI']),
    dict(slug='automotriz', corto='Talleres, hojalatería y refaccionarias.', nombre='Automotriz',
         tipos='Talleres mecánicos, hojalatería y pintura, refaccionarias y lavado de autos.',
         lead='Autos que esperan una refacción, clientes que preguntan «¿ya está?» y presupuestos que cambian. Hacemos visible qué reparación sigue y qué la detiene.',
         voces=['¿Qué reparación sigue y qué la detiene?', '¿Cuánto cotizamos y cuánto se cobró al final?', '¿Qué refacciones tengo y cuáles hay que pedir?', '¿Qué auto se entrega hoy?'],
         piezas=['Cotizador', 'Control de pedidos y cobros', 'Inventario y reorden', 'Procedimiento escrito', 'Agenda de cobranza', 'Tablero semanal'],
         herramientas=['Excel', 'Hojas de Google', 'WhatsApp Business', 'Google Calendar', 'Canva', 'Mercado Pago']),
    dict(slug='turismo-y-hospitalidad', corto='Hoteles pequeños, rentas vacacionales y tours.', nombre='Turismo y hospitalidad',
         tipos='Hoteles pequeños, renta vacacional, tours y restaurantes de la costa y la sierra de Nayarit.',
         lead='Temporadas altas y bajas, reservaciones por WhatsApp y personal que cambia. Te ayudamos a ver reservaciones, cobros y pendientes en una sola vista, y a que cada temporada arranque con el mismo estándar.',
         voces=['¿Qué está reservado y qué falta cobrar?', '¿Me alcanza el dinero para la temporada baja?', '¿Cómo entreno rápido al personal nuevo?', '¿Qué se rentó y cuándo regresa?'],
         piezas=['Flujo a 30, 60 y 90 días', 'Control de pedidos y cobros', 'Procedimiento escrito', 'Tablero semanal', 'Agenda de cobranza', 'Lista de precios o catálogo'],
         herramientas=['Google Calendar', 'WhatsApp Business', 'Hojas de Google', 'Google Maps', 'Instagram', 'Facebook']),
    dict(slug='servicios-profesionales', corto='Consultorios, despachos y estéticas.', nombre='Servicios profesionales y de salud',
         tipos='Consultorios, despachos, estéticas, gimnasios, escuelas y servicios por cita.',
         lead='Tu agenda es tu inventario. Ordenamos citas, cobros y seguimientos para que no se crucen las citas ni se queden pagos sin cobrar.',
         voces=['¿Se me cruzan las citas?', '¿Qué servicio toca y qué falta cobrar?', '¿Quién da seguimiento a cada cliente?', '¿Cuántos clientes regresan?'],
         piezas=['Agenda de cobranza', 'Quién hace qué', 'Tablero semanal', 'Lista de precios o catálogo', 'Registro diario desde el celular', 'Expediente para el contador'],
         herramientas=['Google Calendar', 'WhatsApp Business', 'Hojas de Google', 'Google Forms', 'Notion', 'Zoom']),
]

# ---------------- Soluciones ----------------
SOLUCIONES = [
    dict(slug='orden', nombre='Orden', icono='i-orden', tl='Cada cosa en su lugar.',
         lead='Que las cosas salgan igual aunque tú no estés: precios a la vista, tareas escritas y un responsable para cada pendiente.',
         voces=['Todo depende de mí: los precios están en mi cabeza.', 'Cuando falto, algo sale mal.', 'Me preguntan lo mismo varias veces al día.'],
         entregables=[('Lista de precios o catálogo', 'Con tu marca, en PDF, para que todos den el mismo precio.'),
                      ('Cotizador', 'Decir qué se entrega, cuánto cuesta y hasta cuándo vale el precio.'),
                      ('Procedimiento escrito', 'Una tarea paso a paso, con lista de verificación.'),
                      ('Quién hace qué', 'Mapa de quién hace cada cosa y quién decide.'),
                      ('Expediente para el contador', 'Los documentos que pide tu contador, juntos y a tiempo.'),
                      ('Plantillas protegidas (con Plus)', 'Tu equipo solo cambia textos y precios; el formato no se rompe.')],
         mide=('Pendientes sin responsable', 'Contamos cuántos pendientes no tienen dueño antes de empezar y al entregar. La meta: ninguno.')),
    dict(slug='visibilidad', nombre='Visibilidad', icono='i-vis', tl='Saber qué pasa, a tiempo.',
         lead='Saber cada semana cómo va el negocio, en una sola vista, sin esperar a fin de mes ni leer todas las libretas.',
         voces=['No sé cómo va el negocio hasta fin de mes.', 'No sé si esta semana fue mejor que la pasada.', 'Los números están en varias libretas.'],
         entregables=[('Registro diario desde el celular', 'Una captura corta para guardar el dato antes de olvidarlo.'),
                      ('Tablero semanal', 'Cinco indicadores con gráficas que se actualizan solas.'),
                      ('Control de pedidos y cobros', 'Qué se pidió, qué se entregó y cuánto falta cobrar.'),
                      ('Flujo a 30, 60 y 90 días', 'Ver a tiempo si el dinero alcanzaría.'),
                      ('Inventario y reorden', 'Existencias visibles y aviso para pedir antes de quedarte sin producto.'),
                      ('Resumen de una página (con Plus)', 'Para imprimir o mandar por WhatsApp.')],
         mide=('Dinero previsto a 30, 60 y 90 días', 'Al entregar comparamos contigo lo previsto contra lo que pasó; después lo revisas tú cada semana en tu tablero.')),
    dict(slug='control', nombre='Control', icono='i-ctl', tl='Que lo cobrado cuadre.',
         lead='Que no se te escape dinero sin darte cuenta: la caja cuadra al cierre y cada cliente que te debe tiene fecha de cobro.',
         voces=['Fío y se me olvida cobrar.', 'Al cerrar, la caja no coincide con las ventas.', 'No sé si lo que cobré llegó completo al banco.'],
         entregables=[('Arqueo y cierre de caja', 'Lista de apertura y cierre, con una hoja que suma sola.'),
                      ('Lo cobrado contra lo depositado', 'Comprobar que lo cobrado coincide con lo que entró al banco.'),
                      ('Agenda de cobranza', 'Calendario de cobro ordenado por monto y antigüedad.'),
                      ('Mensajes de cobranza', 'En tres tonos, listos para WhatsApp. Los envías tú.'),
                      ('Formato de salidas y entregas (con Plus)', 'Para saber qué salió, quién lo llevó y quién lo recibió.'),
                      ('Capacitación a tu encargado de caja (con Plus)', 'Para que el cierre salga igual cualquier día.')],
         mide=('Lo cobrado contra lo depositado', 'Lo probamos contigo en un cierre real. Si algo no cuadra, se ve la diferencia y su causa.')),
    dict(slug='mejora-continua', nombre='Mejora continua', icono='i-mejora', tl='Medir, ajustar y volver a medir.',
         lead='Un trabajo no termina al entregarlo: termina cuando tu equipo lo usa solo. Medimos el indicador antes y después; a esa diferencia le llamamos Delta (Δ).',
         voces=['Ya intenté ordenarme y a las dos semanas volvimos a lo mismo.', 'No sé si lo que cambié sirvió de algo.', 'Mi equipo deja de usar los formatos.'],
         entregables=[('Un indicador por trabajo', 'Lo medimos antes de empezar y después de entregar.'),
                      ('Prueba con un caso real', 'Una semana o un cierre real, y ajuste antes de darlo por entregado.'),
                      ('Tu equipo lo usa solo', 'Se da por entregado cuando tu equipo completa un ciclo sin nosotros.'),
                      ('Revisión a las cuatro semanas (con Plus)', 'En Visibilidad, para ajustar los indicadores.'),
                      ('Ciclo de mejora', 'Planear, hacer, verificar y ajustar, al tamaño de tu negocio.'),
                      ('Capacitación', 'Para que tu equipo use lo entregado sin nosotros.')],
         mide=('Delta (Δ)', 'La diferencia entre cómo estaba el indicador y cómo está después. Tú la ves y tú la verificas.')),
    dict(slug='herramientas', nombre='Herramientas', icono='i-herr', tl='Sencillas y adaptadas a tu negocio.',
         lead='No te vendemos software. Partimos de lo que ya usas, en papel o en el celular, y lo dejamos ordenado para que tu equipo lo use solo.',
         voces=['Compré un sistema y nadie lo usa.', 'Tengo todo en Excel, pero nadie lo entiende.', 'Quiero usar inteligencia artificial, pero no sé para qué.'],
         entregables=[('Hojas de cálculo', 'Excel u Hojas de Google con registros que suman solos.'),
                      ('Documentos con tu marca', 'Formatos, listas y tableros en la cuenta de Canva de tu negocio.'),
                      ('WhatsApp Business', 'Mensajes listos, catálogos y recordatorios para tus clientes.'),
                      ('Formularios', 'Captura semanal de 5 minutos desde el celular, por ejemplo con Google Forms.'),
                      ('Sistemas que ya tienes', 'Si ya usas Odoo, CONTPAQi o Aspel, partimos de ahí.'),
                      ('Inteligencia artificial, fácil', 'Asistentes como Claude, ChatGPT o Gemini para redactar y resumir; tú revisas y decides.')],
         mide=('Uso real', 'Una herramienta sirve si tu equipo la usa. Al entregar revisamos contigo si se captura y se consulta.')),
    dict(slug='metodos', nombre='Métodos', icono='i-metodo', tl='Claros, cortos y en tu idioma.',
         lead='Tomamos métodos probados de la mejora continua y los llevamos al tamaño de tu negocio, sin siglas ni papeleo de más.',
         voces=['Los consultores me dejaron un documento que nunca leí.', 'Quiero saber qué hacer el lunes, no una teoría.', 'Necesito que mi equipo entienda el cambio.'],
         entregables=[('Triaje', 'Doce preguntas y un caso real de tu negocio, de punta a punta. Siempre sin costo.'),
                      ('Ficha', 'Un PDF corto: el problema en tus palabras, dos o tres hechos, una acción para hoy y el siguiente paso.'),
                      ('Ticket', 'Un trabajo con precio cerrado y un indicador. Se entrega cuando tu equipo lo usa solo.'),
                      ('Delta', 'La medición de antes y después, para decidir el siguiente paso.'),
                      ('Listas de verificación', 'Para que una tarea salga igual sin depender de la memoria.'),
                      ('Tableros visuales', 'Pocos números, a la vista, revisados cada semana.')],
         mide=('Delta (Δ)', 'El indicador de cada Ticket, antes y después. Tú lo verificas.')),
]

# ---------------- Herramientas de la barra (≥15) ----------------
# Las que tienen ícono libre (Simple Icons, CC0) llevan su slug; las demás se muestran solo con su nombre.
BARRA = [('Excel', None), ('Hojas de Google', 'googlesheets'), ('WhatsApp Business', 'whatsapp'), ('Canva', None),
         ('Odoo', 'odoo'), ('Notion', 'notion'), ('Claude', 'claude'), ('ChatGPT', None), ('Gemini', 'googlegemini'),
         ('Google Drive', 'googledrive'), ('Gmail', 'gmail'), ('Google Calendar', 'googlecalendar'), ('Google Forms', 'googleforms'),
         ('Google Maps', 'googlemaps'), ('CONTPAQi', None), ('Aspel', None), ('Power BI', None), ('Mercado Pago', 'mercadopago'),
         ('Shopify', 'shopify'), ('Zapier', 'zapier'), ('Trello', 'trello'), ('Zoom', 'zoom'), ('Facebook', 'facebook'), ('Instagram', 'instagram')]
